export const galleryInfoHindi = {
  title: 'गैलरी',
  subtitle:
    "हमारी गैलरी के माध्यम से राजस्थान के मनमोहक रेगिस्तानी परिदृश्य और जीवंत सांस्कृतिक अनुभवों की एक झलक।",
  heroImage: '/assets/Images/gallery/Banner.JPG',
  contactButtonText: 'मेरे बारे में',
  contactButtonLink: '/about',
  bookButtonText: 'अभी बुक करें',
  bookButtonLink: 'https://forms.gle/KX871rPaAT5FMqoS6',

  sections: [
    {
      id: 'cultural',
      title: 'राजस्थान की सांस्कृतिक विरासत',
      description:
        "शरवन पटेल के लेंस के माध्यम से राजस्थान की संस्कृति और विरासत के जीवंत ताने-बाने में खुद को डुबोएं। आकर्षक महिलाओं के शानदार परिधानों से लेकर बूढ़े पुरुषों और महिलाओं के चेहरों पर अंकित कालातीत ज्ञान तक, प्रत्येक तस्वीर थार रेगिस्तान और उससे आगे के अनुष्ठानों, परंपराओं और समृद्ध सांस्कृतिक विरासत के सार को कैप्चर करती है।",
      images: [
        { src: '/assets/Images/gallery/gallery-31.JPG', alt: 'सांस्कृतिक छवि 1' },
        { src: '/assets/Images/gallery/gallery-32.JPG', alt: 'सांस्कृतिक छवि 2' },
        { src: '/assets/Images/gallery/gallery-33.JPG', alt: 'सांस्कृतिक छवि 3' },
        { src: '/assets/Images/gallery/gallery-34.JPG', alt: 'सांस्कृतिक छवि 4' },
        { src: '/assets/Images/gallery/gallery-35.JPG', alt: 'सांस्कृतिक छवि 5' },
        { src: '/assets/Images/gallery/gallery-36.jpg', alt: 'सांस्कृतिक छवि 6' },
        { src: '/assets/Images/gallery/gallery-37.JPG', alt: 'सांस्कृतिक छवि 7' },
        { src: '/assets/Images/gallery/gallery-38.JPG', alt: 'सांस्कृतिक छवि 8' },
        { src: '/assets/Images/gallery/gallery-39.JPG', alt: 'सांस्कृतिक छवि 9' },
        { src: '/assets/Images/gallery/gallery-40.JPG', alt: 'सांस्कृतिक छवि 10' },
        { src: '/assets/Images/gallery/gallery-41.JPG', alt: 'सांस्कृतिक छवि 11' },
        { src: '/assets/Images/gallery/gallery-42.JPG', alt: 'सांस्कृतिक छवि 12' },
        { src: '/assets/Images/gallery/gallery-43.JPG', alt: 'सांस्कृतिक छवि 13' },
        { src: '/assets/Images/gallery/gallery-44.JPG', alt: 'सांस्कृतिक छवि 14' },
        { src: '/assets/Images/gallery/gallery-45.JPG', alt: 'सांस्कृतिक छवि 15' },
        { src: '/assets/Images/gallery/gallery-46.JPG', alt: 'सांस्कृतिक छवि 16' },
        { src: '/assets/Images/gallery/gallery-47.JPG', alt: 'सांस्कृतिक छवि 17' },
        { src: '/assets/Images/gallery/gallery-48.JPG', alt: 'सांस्कृतिक छवि 18' },
        { src: '/assets/Images/gallery/gallery-49.JPG', alt: 'सांस्कृतिक छवि 19' },
        { src: '/assets/Images/gallery/gallery-50.JPG', alt: 'सांस्कृतिक छवि 20' },
        { src: '/assets/Images/gallery/gallery-51.JPG', alt: 'सांस्कृतिक छवि 21' },
        { src: '/assets/Images/gallery/gallery-52.JPG', alt: 'सांस्कृतिक छवि 22' },
        { src: '/assets/Images/gallery/gallery-53.JPG', alt: 'सांस्कृतिक छवि 23' },
        { src: '/assets/Images/gallery/gallery-54.JPG', alt: 'सांस्कृतिक छवि 24' },
        { src: '/assets/Images/gallery/gallery-55.JPG', alt: 'सांस्कृतिक छवि 25' },
        { src: '/assets/Images/gallery/gallery-56.JPG', alt: 'सांस्कृतिक छवि 26' },
        { src: '/assets/Images/gallery/gallery-57.JPG', alt: 'सांस्कृतिक छवि 27' },
        { src: '/assets/Images/gallery/gallery-58.JPG', alt: 'सांस्कृतिक छवि 28' },
        { src: '/assets/Images/gallery/gallery-59.JPG', alt: 'सांस्कृतिक छवि 29' },
        { src: '/assets/Images/gallery/gallery-60.JPG', alt: 'सांस्कृतिक छवि 30' },
        { src: '/assets/Images/gallery/gallery-61.JPG', alt: 'सांस्कृतिक छवि 31' },
        { src: '/assets/Images/gallery/gallery-62.JPG', alt: 'सांस्कृतिक छवि 32' },
        { src: '/assets/Images/gallery/gallery-63.JPG', alt: 'सांस्कृतिक छवि 33' },
        { src: '/assets/Images/gallery/gallery-64.JPG', alt: 'सांस्कृतिक छवि 34' },
        { src: '/assets/Images/gallery/gallery-65.JPG', alt: 'सांस्कृतिक छवि 35' },
        { src: '/assets/Images/gallery/gallery-66.JPG', alt: 'सांस्कृतिक छवि 36' },
        { src: '/assets/Images/gallery/gallery-67.JPG', alt: 'सांस्कृतिक छवि 37' },
        { src: '/assets/Images/gallery/gallery-68.JPG', alt: 'सांस्कृतिक छवि 38' },
        { src: '/assets/Images/gallery/gallery-69.JPG', alt: 'सांस्कृतिक छवि 39' },
        { src: '/assets/Images/gallery/gallery-70.JPG', alt: 'सांस्कृतिक छवि 40' },
        { src: '/assets/Images/gallery/gallery-71.JPG', alt: 'सांस्कृतिक छवि 41' },
        { src: '/assets/Images/gallery/gallery-72.JPG', alt: 'सांस्कृतिक छवि 42' },
        { src: '/assets/Images/gallery/gallery-73.JPG', alt: 'सांस्कृतिक छवि 43' },
        { src: '/assets/Images/gallery/gallery-74.JPG', alt: 'सांस्कृतिक छवि 44' },
        { src: '/assets/Images/gallery/gallery-75.jpg', alt: 'सांस्कृतिक छवि 45' },
        { src: '/assets/Images/gallery/gallery-76.jpg', alt: 'सांस्कृतिक छवि 46' },
      ],
    },
    {
      id: 'gib',
      title: 'प्राकृतिक आवास में ग्रेट इंडियन बस्टर्ड',
      description:
        "शरवन पटेल के लेंस के माध्यम से ग्रेट इंडियन बस्टर्ड की अपने प्राकृतिक आवास में भव्य उपस्थिति का साक्षी बनें। प्रत्येक तस्वीर इस लुप्तप्राय प्रजाति की भव्यता और भेद्यता को समेटती है, जो थार रेगिस्तान के सबसे प्रतिष्ठित निवासियों में से एक के जीवन की एक दुर्लभ झलक प्रदान करती है।",
      images: [
        { src: '/assets/Images/GIB-1.jpg', alt: 'ग्रेट इंडियन बस्टर्ड छवि 1' },
        { src: '/assets/Images/GIB-2.jpeg', alt: 'ग्रेट इंडियन बस्टर्ड छवि 2' },
        { src: '/assets/Images/GIB-3.jpeg', alt: 'ग्रेट इंडियन बस्टर्ड छवि 3' },
        { src: '/assets/Images/GIB-4.jpg', alt: 'ग्रेट इंडियन बस्टर्ड छवि 4' },
        { src: '/assets/Images/GIB-5.jpg', alt: 'ग्रेट इंडियन बस्टर्ड छवि 5' },
      ],
    },
    {
      id: 'animals',
      title: 'अन्य जानवर',
      description:
        "शरवन पटेल के लेंस के माध्यम से गैर-मानव निवासियों की मनमोहक दुनिया का अन्वेषण करें। पक्षियों की सुंदर उड़ान से लेकर जानवरों के मोहक जीवन तक, प्रत्येक तस्वीर थार रेगिस्तान के दिल में पनपने वाले विविध और जीवंत जीवन की एक अनूठी कहानी बताती है।",
      images: [
        { src: '/assets/Images/other-1.jpg', alt: 'जानवर छवि 1' },
        { src: '/assets/Images/other-2.jpg', alt: 'जानवर छवि 2' },
        { src: '/assets/Images/other-3.jpg', alt: 'जानवर छवि 3' },
        { src: '/assets/Images/other-4.jpg', alt: 'जानवर छवि 4' },
        { src: '/assets/Images/other-5.jpg', alt: 'जानवर छवि 5' },
        { src: '/assets/Images/other-6.jpg', alt: 'जानवर छवि 6' },
        { src: '/assets/Images/other-7.jpg', alt: 'जानवर छवि 7' },
        { src: '/assets/Images/other-8.jpg', alt: 'जानवर छवि 8' },
        { src: '/assets/Images/other-9.jpg', alt: 'जानवर छवि 9' },
        { src: '/assets/Images/other-10.jpg', alt: 'जानवर छवि 10' },
        { src: '/assets/Images/other-11.jpeg', alt: 'जानवर छवि 11' },
        { src: '/assets/Images/other-12.jpeg', alt: 'जानवर छवि 12' },
        { src: '/assets/Images/other-13.jpeg', alt: 'जानवर छवि 13' },
        { src: '/assets/Images/other-14.jpeg', alt: 'जानवर छवि 14' },
        { src: '/assets/Images/other-15.jpg', alt: 'जानवर छवि 15' },
        { src: '/assets/Images/other-16.jpg', alt: 'जानवर छवि 16' },
        { src: '/assets/Images/other-17.jpg', alt: 'जानवर छवि 17' },
        { src: '/assets/Images/other-18.JPG', alt: 'जानवर छवि 18' },
        { src: '/assets/Images/other-19.jpg', alt: 'जानवर छवि 19' },
        { src: '/assets/Images/other-20.jpg', alt: 'जानवर छवि 20' },
        { src: '/assets/Images/others-21.JPG', alt: 'जानवर छवि 21' },
        { src: '/assets/Images/others-22.jpg', alt: 'जानवर छवि 22' },
        { src: '/assets/Images/others-23.jpg', alt: 'जानवर छवि 23' },
        { src: '/assets/Images/others-24.jpg', alt: 'जानवर छवि 24' },
        { src: '/assets/Images/others-25.jpg', alt: 'जानवर छवि 25' },
        { src: '/assets/Images/others-26.jpg', alt: 'जानवर छवि 26' },
        { src: '/assets/Images/others-27.jpg', alt: 'जानवर छवि 27' },
        { src: '/assets/Images/others-28.jpg', alt: 'जानवर छवि 28' },
        { src: '/assets/Images/others-29.jpg', alt: 'जानवर छवि 29' },
        { src: '/assets/Images/others-30.jpg', alt: 'जानवर छवि 30' },
        { src: '/assets/Images/others-31.jpg', alt: 'जानवर छवि 31' },
        { src: '/assets/Images/others-32.jpg', alt: 'जानवर छवि 32' },
        { src: '/assets/Images/others-34.JPG', alt: 'जानवर छवि 34' },
        { src: '/assets/Images/others-35.jpg', alt: 'जानवर छवि 35' },
        { src: '/assets/Images/others-36.jpg', alt: 'जानवर छवि 36' },
        { src: '/assets/Images/others-37.jpg', alt: 'जानवर छवि 37' },
        { src: '/assets/Images/others-38.jpg', alt: 'जानवर छवि 38' },
        { src: '/assets/Images/others-39.JPG', alt: 'जानवर छवि 39' },
        { src: '/assets/Images/others-40.JPG', alt: 'जानवर छवि 40' },
        { src: '/assets/Images/others-41.JPG', alt: 'जानवर छवि 41' },
        { src: '/assets/Images/others-42.JPG', alt: 'जानवर छवि 42' },
        { src: '/assets/Images/others-43.JPG', alt: 'जानवर छवि 43' },
        { src: '/assets/Images/others-44.jpg', alt: 'जानवर छवि 44' },
        { src: '/assets/Images/others-45.jpg', alt: 'जानवर छवि 45' },
        { src: '/assets/Images/others-46.jpg', alt: 'जानवर छवि 46' },
      ],
    },
  ],
};