export const galleryInfo = {
  title: 'Gallery',
  subtitle:
    "A Glimpse of Rajasthan's Enchanting Desert Landscape and Vibrant Cultural Experiences through our Gallery.",
  heroImage: '/assets/Images/gallery/Banner.JPG',
  contactButtonText: 'About me',
  contactButtonLink: '/about',
  bookButtonText: 'Book now',
  bookButtonLink: 'https://forms.gle/KX871rPaAT5FMqoS6',

  sections: [
    {
      id: 'cultural',
      title: 'Cultural Tapestry of Rajasthan',
      description:
        "Immerse yourself in the vivid tapestry of Rajasthan's culture and heritage through Sharvan Patel's lens. From the resplendent attire of alluring women to the timeless wisdom etched on the faces of old men and women, each photograph captures the essence of rituals, traditions, and the rich cultural heritage of the Thar Desert and beyond.",
      images: [
        { src: '/assets/Images/gallery/gallery-31.JPG', alt: 'Cultural image 1' },
        { src: '/assets/Images/gallery/gallery-32.JPG', alt: 'Cultural image 2' },
        { src: '/assets/Images/gallery/gallery-33.JPG', alt: 'Cultural image 3' },
        { src: '/assets/Images/gallery/gallery-34.JPG', alt: 'Cultural image 4' },
        { src: '/assets/Images/gallery/gallery-35.JPG', alt: 'Cultural image 5' },
        { src: '/assets/Images/gallery/gallery-36.jpg', alt: 'Cultural image 6' },
        { src: '/assets/Images/gallery/gallery-37.JPG', alt: 'Cultural image 7' },
        { src: '/assets/Images/gallery/gallery-38.JPG', alt: 'Cultural image 8' },
        { src: '/assets/Images/gallery/gallery-39.JPG', alt: 'Cultural image 9' },
        { src: '/assets/Images/gallery/gallery-40.JPG', alt: 'Cultural image 10' },
        { src: '/assets/Images/gallery/gallery-41.JPG', alt: 'Cultural image 11' },
        { src: '/assets/Images/gallery/gallery-42.JPG', alt: 'Cultural image 12' },
        { src: '/assets/Images/gallery/gallery-43.JPG', alt: 'Cultural image 13' },
        { src: '/assets/Images/gallery/gallery-44.JPG', alt: 'Cultural image 14' },
        { src: '/assets/Images/gallery/gallery-45.JPG', alt: 'Cultural image 15' },
        { src: '/assets/Images/gallery/gallery-46.JPG', alt: 'Cultural image 16' },
        { src: '/assets/Images/gallery/gallery-47.JPG', alt: 'Cultural image 17' },
        { src: '/assets/Images/gallery/gallery-48.JPG', alt: 'Cultural image 18' },
        { src: '/assets/Images/gallery/gallery-49.JPG', alt: 'Cultural image 19' },
        { src: '/assets/Images/gallery/gallery-50.JPG', alt: 'Cultural image 20' },
        { src: '/assets/Images/gallery/gallery-51.JPG', alt: 'Cultural image 21' },
        { src: '/assets/Images/gallery/gallery-52.JPG', alt: 'Cultural image 22' },
        { src: '/assets/Images/gallery/gallery-53.JPG', alt: 'Cultural image 23' },
        { src: '/assets/Images/gallery/gallery-54.JPG', alt: 'Cultural image 24' },
        { src: '/assets/Images/gallery/gallery-55.JPG', alt: 'Cultural image 25' },
        { src: '/assets/Images/gallery/gallery-56.JPG', alt: 'Cultural image 26' },
        { src: '/assets/Images/gallery/gallery-57.JPG', alt: 'Cultural image 27' },
        { src: '/assets/Images/gallery/gallery-58.JPG', alt: 'Cultural image 28' },
        { src: '/assets/Images/gallery/gallery-59.JPG', alt: 'Cultural image 29' },
        { src: '/assets/Images/gallery/gallery-60.JPG', alt: 'Cultural image 30' },
        { src: '/assets/Images/gallery/gallery-61.JPG', alt: 'Cultural image 31' },
        { src: '/assets/Images/gallery/gallery-62.JPG', alt: 'Cultural image 32' },
        { src: '/assets/Images/gallery/gallery-63.JPG', alt: 'Cultural image 33' },
        { src: '/assets/Images/gallery/gallery-64.JPG', alt: 'Cultural image 34' },
        { src: '/assets/Images/gallery/gallery-65.JPG', alt: 'Cultural image 35' },
        { src: '/assets/Images/gallery/gallery-66.JPG', alt: 'Cultural image 36' },
        { src: '/assets/Images/gallery/gallery-67.JPG', alt: 'Cultural image 37' },
        { src: '/assets/Images/gallery/gallery-68.JPG', alt: 'Cultural image 38' },
        { src: '/assets/Images/gallery/gallery-69.JPG', alt: 'Cultural image 39' },
        { src: '/assets/Images/gallery/gallery-70.JPG', alt: 'Cultural image 40' },
        { src: '/assets/Images/gallery/gallery-71.JPG', alt: 'Cultural image 41' },
        { src: '/assets/Images/gallery/gallery-72.JPG', alt: 'Cultural image 42' },
        { src: '/assets/Images/gallery/gallery-73.JPG', alt: 'Cultural image 43' },
        { src: '/assets/Images/gallery/gallery-74.JPG', alt: 'Cultural image 44' },
        { src: '/assets/Images/gallery/gallery-75.jpg', alt: 'Cultural image 45' },
        { src: '/assets/Images/gallery/gallery-76.jpg', alt: 'Cultural image 46' },
      ],
    },
    {
      id: 'gib',
      title: 'Great Indian Bustard in the Wild',
      description:
        "Witness the majestic presence of the Great Indian Bustard in its natural habitat through the lens of Sharvan Patel. Each photograph encapsulates the grandeur and vulnerability of this endangered species, offering a rare glimpse into the life of one of the Thar Desert's most iconic inhabitants.",
      images: [
        { src: '/assets/Images/GIB-1.jpg', alt: 'Great Indian Bustard image 1' },
        { src: '/assets/Images/GIB-2.jpeg', alt: 'Great Indian Bustard image 2' },
        { src: '/assets/Images/GIB-3.jpeg', alt: 'Great Indian Bustard image 3' },
        { src: '/assets/Images/GIB-4.jpg', alt: 'Great Indian Bustard image 4' },
        { src: '/assets/Images/GIB-5.jpg', alt: 'Great Indian Bustard image 5' },
      ],
    },
    {
      id: 'animals',
      title: 'Other Animals',
      description:
        "Explore the enchanting world of non-human inhabitants through Sharvan Patel's lens. From the graceful flight of birds to the mesmerizing life of animals, each photograph tells a unique story of the diverse and vibrant life that thrives in the heart of Thar Desert.",
      images: [
        { src: '/assets/Images/other-1.jpg', alt: 'Animal image 1' },
        { src: '/assets/Images/other-2.jpg', alt: 'Animal image 2' },
        { src: '/assets/Images/other-3.jpg', alt: 'Animal image 3' },
        { src: '/assets/Images/other-4.jpg', alt: 'Animal image 4' },
        { src: '/assets/Images/other-5.jpg', alt: 'Animal image 5' },
        { src: '/assets/Images/other-6.jpg', alt: 'Animal image 6' },
        { src: '/assets/Images/other-7.jpg', alt: 'Animal image 7' },
        { src: '/assets/Images/other-8.jpg', alt: 'Animal image 8' },
        { src: '/assets/Images/other-9.jpg', alt: 'Animal image 9' },
        { src: '/assets/Images/other-10.jpg', alt: 'Animal image 10' },
        { src: '/assets/Images/other-11.jpeg', alt: 'Animal image 11' },
        { src: '/assets/Images/other-12.jpeg', alt: 'Animal image 12' },
        { src: '/assets/Images/other-13.jpeg', alt: 'Animal image 13' },
        { src: '/assets/Images/other-14.jpeg', alt: 'Animal image 14' },
        { src: '/assets/Images/other-15.jpg', alt: 'Animal image 15' },
        { src: '/assets/Images/other-16.jpg', alt: 'Animal image 16' },
        { src: '/assets/Images/other-17.jpg', alt: 'Animal image 17' },
        { src: '/assets/Images/other-18.JPG', alt: 'Animal image 18' },
        { src: '/assets/Images/other-19.jpg', alt: 'Animal image 19' },
        { src: '/assets/Images/other-20.jpg', alt: 'Animal image 20' },
        { src: '/assets/Images/others-21.JPG', alt: 'Animal image 21' },
        { src: '/assets/Images/others-22.jpg', alt: 'Animal image 22' },
        { src: '/assets/Images/others-23.jpg', alt: 'Animal image 23' },
        { src: '/assets/Images/others-24.jpg', alt: 'Animal image 24' },
        { src: '/assets/Images/others-25.jpg', alt: 'Animal image 25' },
        { src: '/assets/Images/others-26.jpg', alt: 'Animal image 26' },
        { src: '/assets/Images/others-27.jpg', alt: 'Animal image 27' },
        { src: '/assets/Images/others-28.jpg', alt: 'Animal image 28' },
        { src: '/assets/Images/others-29.jpg', alt: 'Animal image 29' },
        { src: '/assets/Images/others-30.jpg', alt: 'Animal image 30' },
        { src: '/assets/Images/others-31.jpg', alt: 'Animal image 31' },
        { src: '/assets/Images/others-32.jpg', alt: 'Animal image 32' },
        { src: '/assets/Images/others-34.JPG', alt: 'Animal image 34' },
        { src: '/assets/Images/others-35.jpg', alt: 'Animal image 35' },
        { src: '/assets/Images/others-36.jpg', alt: 'Animal image 36' },
        { src: '/assets/Images/others-37.jpg', alt: 'Animal image 37' },
        { src: '/assets/Images/others-38.jpg', alt: 'Animal image 38' },
        { src: '/assets/Images/others-39.JPG', alt: 'Animal image 39' },
        { src: '/assets/Images/others-40.JPG', alt: 'Animal image 40' },
        { src: '/assets/Images/others-41.JPG', alt: 'Animal image 41' },
        { src: '/assets/Images/others-42.JPG', alt: 'Animal image 42' },
        { src: '/assets/Images/others-43.JPG', alt: 'Animal image 43' },
        { src: '/assets/Images/others-44.jpg', alt: 'Animal image 44' },
        { src: '/assets/Images/others-45.jpg', alt: 'Animal image 45' },
        { src: '/assets/Images/others-46.jpg', alt: 'Animal image 46' },
      ],
    },
  ],
};
